# =========================
# DB
# =========================
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/dodo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=0418

# =========================
# Mail
# =========================
# spring.mail.username=
# spring.mail.password=

# =========================
# Kakao OAuth2
# =========================
spring.security.oauth2.client.registration.kakao.client-id=ec7204588f5ee363c59adaadc9851091
spring.security.oauth2.client.registration.kakao.client-secret=E3tq8F4RM1wnviFrTez4LQrKd9IEkEKF

